### ISSUE TITLE
bug: multiplayer crashes unexpectedly

### ISSUE THREAD

**Issue by tarunregmi** [thomas-mauran/chess-tui#122]
Multiplayer crashes if we access (`192.168.x.x:2308`) from external clients (like browser, ...). It crashes with the following errors:

```bash
thread '<unnamed>' panicked at src/server/game_server.rs:139:53:
called `Result::unwrap()` on an `Err` value: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
```

Or,

```bash
thread 'main' panicked at src/utils.rs:83:37:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by thomas-mauran** [comment]
Can you specify what you mean by browser so I can try to reproduce ?

**Comment by tarunregmi** [comment]
Follow following steps:
1. open `Multiplayer` in `HOSTING` mode
2. choose `color`
3. then now you are at page waiting for opponent connection using your IP address (`192.168.x.x:2308`)
4. now visit `192.168.x.x:2308` form any web browser to see `error`

**Comment by thomas-mauran** [comment]
This is kind of normal since 192.168.x.x:2308 is opening a tcp stream, connecting with a browser will send an http request to the endpoint which is not handled at all right now. The only correct way to play a multiplayer game is to use the `join` method from another cli with chess-tui
